version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
        - ENVIRONMENT=production
        - SECRET_KEY=ehsuv_!j0leim8$fg@@ly6jsx(kh1szf9cdavu+6&zh+5xd6*6
        - DEBUG=0
        - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51HU7V9A3lPSgAZTaYgWnQOyjMzwe7KtXuJEMd80MGQdwQMc4DBCk1qt2T56oDPn8jOtk7aLzKmGCJ5dRYYMCWOAz00S8GqHgiK
        - STRIPE_TEST_SECRET_KEY=sk_test_51HU7V9A3lPSgAZTaEXFYCRn4hm9mbBj2tn0uAR7bDXVz8xkMRnp8h3EcQkLFLBhPFnuRYGRF4N6at4iUgYQ2tZgR00wxZOxY9z
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
